FROM postgres:13

ENV POSTGRES_DB=salary_db
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=example

COPY sql/00_backfill/00_backfill.sql /docker-entrypoint-initdb.d/
COPY sql/00_backfill/ds_salaries.csv /docker-entrypoint-initdb.d/
